version: '2'
services:
  base:
    build: .
    env_file: .env
    volumes:
      - ./data:/app/data/

  gateway:
    restart: unless-stopped
    extends: base
    command: python manage.py start_gateway

  admin:
    restart: unless-stopped
    extends: base
    environment:
      DEBUG: 'false'
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
