# Generated by Django 2.0.7 on 2018-07-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=10, default=0, max_digits=19, null=True, verbose_name='Currency Amount')),
                ('bts_name', models.CharField(max_length=100, null=True)),
                ('eos_name', models.CharField(max_length=100, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('tokens_emitted', models.BooleanField(default=False, verbose_name='Tokens are emitted')),
                ('sys_message', models.TextField()),
            ],
        ),
    ]
